<!doctype html>
  <head>
  <title>Burgess Metals  - Sheetmetal Services |Tampa FL</title>
    <link rel="stylesheet" href="styles.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="application-name" content="Burgess Metals">
<meta name="description" content="Burgess Metals, Inc.  Serving Tampa Bay Area since 1991">
<meta name="keywords" content="Sheet Metal Duct Tampa FL, sheetmetal, sheetmetal fab tampa fl">
<meta name="author" content="Michelle Anderson Burgess,Michelle Burgess">
<meta charset="UTF-8">
<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
  </head>
  <body>
    <div class="site">

      <!-- Header -->

      <header class="group">
        <div class="logo">
          <h1>Burgess Metals<em>Sheet metal Services</em></h1>
        </div>
        <nav>
          <ul>
            <li class="active"><a href="index.html">Home</a></li>
            <li><a href="services.html">Services</a></li>
            <li><a href="coordination.html">Coordination</a></li>
            <li><a href="Contactus.html">Contact Us</a></li>
          </ul>
        </nav>
        
      </header>

      <!-- Banner -->

      <section class="banner">
      	
        <div class="banner-caption">
          <h2>fabrication and installation</h2>
          <p>of commercial duct systems</p>
        </div>
      </section>

      <!-- Main -->

      <section class="group main">

        <!-- Content -->

        <div class="primary content">
          <div class="inner">
           
     <p> At <strong>Burgess Metals</strong>, we specialize in Industrial and Commercial Sheet Metal ductwork system installations.</p>    
     <p>We are Motivated, through customer satisfaction, to be your sheet metal subcontractor of choice. </p>  
     <p><strong>Burgess Metals</strong> is a Safety conscious, and Safety First sheet metal subcontractor and <strong>Safety</strong> is at the forefront of our operations.</p>   
            	
     <p>Our exemplary computerized drafting department brings over 30 years of MEP coordination experience to each project we do and will make a huge impact on your project.</p>  
     
          </div>
        </div>

        <!-- Sidebar -->

      <aside class="secondary sidebar">
         <div class="inner sidebar-inner">
            <h3>Our Credentials</h3>
            <ul>
               <li>Bonded</li>
              <li>Insured</li>
              <li>Licensed by the State of Florida, CSC1110295</li>
              <li>The office staff is able to complete and execute any contract requirements of our customers</li>
              
            </ul>
          </div>
          <div class="inner sidebar-inner">
            <!-- <h3>Our Team</h3>

            <ul>
              <li class="sidebar-inner-image">
                <a href="#" class="group sidebar-inner-marty">
                  <h5>Marty Burgess</h5>
                </a>
              </li>
              <li class="sidebar-inner-image">
                <a href="#" class="group sidebar-inner-michelle">
                  <h5>Michelle Burgess</h5>
                </a>
              </li>
              
            </ul>-->
          </div>
        </aside>
      </section>

      <!-- Footer -->

      <footer>
        <h4>Copyright &copy; 2013&nbsp;&nbsp;&nbsp; Burgess Metals, Inc..&nbsp;&nbsp;&nbsp; All Rights Reserved.</h2>
      </footer>

    </div>
  </body>
</html>
